// <auto-generated />
using LigaProEcuador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LigaProEcuador.Migrations
{
    [DbContext(typeof(LigaProEcuadorContext))]
    [Migration("20241020233817_Migracion1")]
    partial class Migracion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LigaProEcuador.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("AceptaExtranjeros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Titulos")
                        .HasColumnType("int");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipo");

                    b.HasData(
                        new
                        {
                            IdEquipo = 1,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Guayaquil",
                            Estadio = "Estadio Banco Pichincha",
                            NombreEquipo = "Barcelona SC",
                            Titulos = 16
                        },
                        new
                        {
                            IdEquipo = 2,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Guayaquil",
                            Estadio = "Estadio George Capwell Banco del Austro",
                            NombreEquipo = "CS Emelec",
                            Titulos = 14
                        },
                        new
                        {
                            IdEquipo = 3,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Quito",
                            Estadio = "Estadio Cooprogreso Gonzalo Pozo Ripalda",
                            NombreEquipo = "Sociedad Deportiva Aucas",
                            Titulos = 1
                        },
                        new
                        {
                            IdEquipo = 4,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Quito",
                            Estadio = "Estadio Rodrigo Paz Delgado",
                            NombreEquipo = "Liga Deportiva Universitaria",
                            Titulos = 12
                        },
                        new
                        {
                            IdEquipo = 5,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Quito",
                            Estadio = "Estadio Olímpico Atahualpa",
                            NombreEquipo = "Club Deportivo El Nacional",
                            Titulos = 13
                        },
                        new
                        {
                            IdEquipo = 6,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Manta",
                            Estadio = "Estadio Jocay",
                            NombreEquipo = "Delfín Sporting Club",
                            Titulos = 1
                        },
                        new
                        {
                            IdEquipo = 7,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Cuenca",
                            Estadio = "Banco del Austro Alejandro Serrano Aguilar",
                            NombreEquipo = "Club Deportivo Cuenca",
                            Titulos = 1
                        },
                        new
                        {
                            IdEquipo = 8,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Quito",
                            Estadio = "Estadio Olímpico Atahualpa",
                            NombreEquipo = "Club Universidad Católica",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 9,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Ambato",
                            Estadio = "Estadio Universidad Indoamérica Bellavista",
                            NombreEquipo = "Club Deportivo Macará",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 10,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Quito",
                            Estadio = "Estadio Banco Guayaquil",
                            NombreEquipo = "Club Independiente del Valle",
                            Titulos = 6
                        },
                        new
                        {
                            IdEquipo = 11,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Ambato",
                            Estadio = "Estadio Universidad Indoamérica Bellavista",
                            NombreEquipo = "Club Técnico Universitario",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 12,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Machala",
                            Estadio = "Estadio 9 de mayo",
                            NombreEquipo = "Orense Sporting Club",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 13,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Quito",
                            Estadio = "Estadio Olímpico Atahualpa",
                            NombreEquipo = "Cumbayá Fútbol Club",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 14,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Ambato",
                            Estadio = "Cooperativa de Ahorro y Crédito Mushuc Runa",
                            NombreEquipo = "Mushuc Runa",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 15,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Ibarra",
                            Estadio = "Estadio Olímpico de Ibarra",
                            NombreEquipo = "Imbabura",
                            Titulos = 0
                        },
                        new
                        {
                            IdEquipo = 16,
                            AceptaExtranjeros = "si",
                            CiudadEquipo = "Loja",
                            Estadio = "Estadio Reina del Cisne",
                            NombreEquipo = "Libertad Fútbol Club",
                            Titulos = 0
                        });
                });

            modelBuilder.Entity("LigaProEcuador.Models.Estadio", b =>
                {
                    b.Property<int>("IdEstadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadio"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("CiudadEstadio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.HasKey("IdEstadio");

                    b.HasIndex("IdEquipo");

                    b.ToTable("Estadio");

                    b.HasData(
                        new
                        {
                            IdEstadio = 1,
                            Capacidad = 59283,
                            CiudadEstadio = "Guayaquil",
                            Direccion = "Av. Barcelona",
                            IdEquipo = 1
                        },
                        new
                        {
                            IdEstadio = 2,
                            Capacidad = 40000,
                            CiudadEstadio = "Guayaquil",
                            Direccion = "Gral. José A.Gómez",
                            IdEquipo = 2
                        },
                        new
                        {
                            IdEstadio = 3,
                            Capacidad = 18799,
                            CiudadEstadio = "Quito",
                            Direccion = "Av. Rumichaca Ñan",
                            IdEquipo = 3
                        },
                        new
                        {
                            IdEstadio = 4,
                            Capacidad = 41575,
                            CiudadEstadio = "Quito",
                            Direccion = "Av. John F. Kennedy 817",
                            IdEquipo = 4
                        },
                        new
                        {
                            IdEstadio = 5,
                            Capacidad = 38258,
                            CiudadEstadio = "Quito",
                            Direccion = "Av. Naciones Unidas",
                            IdEquipo = 5
                        },
                        new
                        {
                            IdEstadio = 6,
                            Capacidad = 22000,
                            CiudadEstadio = "Manta",
                            Direccion = "27PW+FRW",
                            IdEquipo = 6
                        },
                        new
                        {
                            IdEstadio = 7,
                            Capacidad = 18549,
                            CiudadEstadio = "Cuenca",
                            Direccion = "Av. del Estadio",
                            IdEquipo = 7
                        },
                        new
                        {
                            IdEstadio = 8,
                            Capacidad = 38258,
                            CiudadEstadio = "Quito",
                            Direccion = "Av. Naciones Unidas",
                            IdEquipo = 8
                        },
                        new
                        {
                            IdEstadio = 9,
                            Capacidad = 16467,
                            CiudadEstadio = "Ambato",
                            Direccion = "Av Bolivariana",
                            IdEquipo = 9
                        },
                        new
                        {
                            IdEstadio = 10,
                            Capacidad = 12000,
                            CiudadEstadio = "Quito",
                            Direccion = "Complejo Independiente del Valle",
                            IdEquipo = 10
                        },
                        new
                        {
                            IdEstadio = 11,
                            Capacidad = 16467,
                            CiudadEstadio = "Ambato",
                            Direccion = "Av Bolivariana",
                            IdEquipo = 11
                        },
                        new
                        {
                            IdEstadio = 12,
                            Capacidad = 16500,
                            CiudadEstadio = "Machala",
                            Direccion = "Avenida de Las Palmeras 919",
                            IdEquipo = 12
                        },
                        new
                        {
                            IdEstadio = 13,
                            Capacidad = 38258,
                            CiudadEstadio = "Quito",
                            Direccion = "Av. Naciones Unidas",
                            IdEquipo = 13
                        },
                        new
                        {
                            IdEstadio = 14,
                            Capacidad = 8200,
                            CiudadEstadio = "Ambato",
                            Direccion = "Via Ambato Guaranda, San Alfonso de Chibuleo",
                            IdEquipo = 14
                        },
                        new
                        {
                            IdEstadio = 15,
                            Capacidad = 17300,
                            CiudadEstadio = "Ibarra",
                            Direccion = "Av. Jaime Roldos Aguilera y, Sánchez y Cifuentes",
                            IdEquipo = 15
                        },
                        new
                        {
                            IdEstadio = 16,
                            Capacidad = 14935,
                            CiudadEstadio = "Loja",
                            Direccion = "avenida Emiliano Ortega y calle Azuay",
                            IdEquipo = 16
                        });
                });

            modelBuilder.Entity("LigaProEcuador.Models.Jugador", b =>
                {
                    b.Property<int>("IdJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJugador"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdJugador");

                    b.HasIndex("IdEquipo");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("LigaProEcuador.Models.Estadio", b =>
                {
                    b.HasOne("LigaProEcuador.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("LigaProEcuador.Models.Jugador", b =>
                {
                    b.HasOne("LigaProEcuador.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
